name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-15
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "generic/platform=iOS Simulator"
          - "generic/platform=tvOS Simulator"
          - "generic/platform=watchOS Simulator"
          - "generic/platform=visionOS Simulator"
    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme EditorConfig -destination "${{ matrix.destination }}" test | xcbeautify

  linux-test:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: swift test
